name: bitcoin_flutter
description: A dart Bitcoin library for Flutter. BIP32, BIP39, P2PKH integration.
version: 2.1.0
homepage: https://github.com/anicdh
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bip39: ^1.0.6
  bip32: ^2.0.0
  pointycastle: ^3.6.0
  hex: ^0.2.0
  bs58check: ^1.0.2
  bech32:
    git:
      url: https://github.com/saltrafael/bech32.git
      ref: bech32m
  elliptic:
    git:
      url: https://github.com/cake-tech/dart-elliptic
      ref: silent-payments

dev_dependencies:
  test: ^1.24.9

dependency_overrides:
  convert: ^3.0.0
  crypto: ^3.0.0
  hex: ^0.2.0
